// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type AuthGroup struct {
	ID   int32
	Name string
}

type AuthGroupPermission struct {
	ID           int64
	GroupID      int32
	PermissionID int32
}

type AuthPermission struct {
	ID            int32
	Name          string
	ContentTypeID int32
	Codename      string
}

type AuthUser struct {
	ID          int32
	Password    string
	LastLogin   sql.NullTime
	IsSuperuser bool
	Username    string
	FirstName   string
	LastName    string
	Email       string
	IsStaff     bool
	IsActive    bool
	DateJoined  time.Time
}

type AuthUserGroup struct {
	ID      int64
	UserID  int32
	GroupID int32
}

type AuthUserUserPermission struct {
	ID           int64
	UserID       int32
	PermissionID int32
}

type ChainMmRel struct {
	ID      int64
	ChainID int64
	MmID    int64
}

type ChainSetting struct {
	ID                      int64
	ChainID                 int64
	SettingsSellQuantity    sql.NullString
	SettingsSlippage        sql.NullString
	SettingsGasBoost        sql.NullString
	SettingsBuyQuantity     sql.NullString
	SettingsGasMaxPriceBuy  sql.NullString
	SettingsGasMaxPriceSell sql.NullString
	SettingsMarketMakerID   sql.NullInt64
	DateCreation            sql.NullTime
	UserID                  int64
}

type DjangoAdminLog struct {
	ID            int32
	ActionTime    time.Time
	ObjectID      sql.NullString
	ObjectRepr    string
	ActionFlag    uint16
	ChangeMessage string
	ContentTypeID sql.NullInt32
	UserID        int32
}

type DjangoContentType struct {
	ID       int32
	AppLabel string
	Model    string
}

type DjangoMigration struct {
	ID      int64
	App     string
	Name    string
	Applied time.Time
}

type DjangoSession struct {
	SessionKey  string
	SessionData string
	ExpireDate  time.Time
}

type MmSetting struct {
	ID                  int64
	Enabled             sql.NullInt32
	MinTimeBetweenTrade sql.NullInt32
	MaxTimeBetweenTrade sql.NullInt32
	SellQuantity        sql.NullString
	Slippage            sql.NullString
	GasBoost            sql.NullString
	BuyQuantity         sql.NullString
	GasMaxPriceBuy      sql.NullString
	GasMaxPriceSell     sql.NullString
	LastTradeDate       sql.NullTime
}

type ReferralFeeDatum struct {
	ID           int64
	ChainID      int64
	FeeClaimed   sql.NullString
	FeePending   sql.NullString
	DateCreation sql.NullTime
	OwnerID      int64
}

type ReferralRel struct {
	ID       int64
	Dateref  sql.NullTime
	Referee  int64
	Referrer int64
}

type TelegramUser struct {
	UserID                  int64
	Username                sql.NullString
	Name                    sql.NullString
	Language                string
	IsEnabled               sql.NullInt32
	IsEnabledForAutotrading sql.NullInt32
	SettingsDefaultChain    sql.NullInt32
	DateCreation            sql.NullTime
	Referralcode            sql.NullString
}

type TradeDatum struct {
	ID            int64
	TradeType     string
	TradeCurrency string
	TradeData     string
	DateCreation  sql.NullTime
	WalletAddress string
}

type TradeSetting struct {
	ID              int64
	ContractAddress string
	IsWhitelisted   sql.NullInt32
	DateCreation    sql.NullTime
	OwnerID         int64
}

type WalletDatum struct {
	ID            int64
	WalletAddress string
	Pkey          string
	PkeyIv        sql.NullString
	WalletType    string
	IsEnabled     sql.NullInt32
	DateCreation  sql.NullTime
	Owner         int64
}
